import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "@/components/Footer/Footer";
import "./layout.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="page">
            <NavBar />
            <main className="main">
                <div className='displayDiv'>
                    {children}
                </div>
            </main>
            <Footer />
        </div>

          </body>
    </html>
  );
}
